// GENERATED by tool/ocr_catalog.dart; do not edit.
// tessdata_fast 87416418657359cb625c412a48b6e1d6d41c29bd
// tessdata_best e12c65a915945e4c28e237a9b52bc4a8f39a0cec

import 'package:niman/src/ocr/ocr_language.dart';

/// The tessdata_fast commit the catalog pins.
const String tessdataFastCommit = '87416418657359cb625c412a48b6e1d6d41c29bd';

/// The tessdata_best commit the catalog pins.
const String tessdataBestCommit = 'e12c65a915945e4c28e237a9b52bc4a8f39a0cec';

/// Every language the OCR offers, by code.
const List<OcrLanguage> ocrLanguages = [
  OcrLanguage(
    'afr',
    native: 'Afrikaans',
    english: 'Afrikaans',
    fast: (
      bytes: 2652786,
      sha256:
          '126d480bfae95be2a911ed4916465e27bde75fea2da631e21b96762e5f239646',
    ),
    best: (
      bytes: 12800552,
      sha256:
          '6f80b369205a51298a2113c662585d52dfc81bb9331c21845538cec959ebe09a',
    ),
  ),
  OcrLanguage(
    'amh',
    native: 'አማርኛ',
    english: 'Amharic',
    fast: (
      bytes: 5470094,
      sha256:
          '3ec3311833a108e07d58a1152b00c0cf1848752e4f85769d46e8ca2b718a2ccc',
    ),
    best: (
      bytes: 8389639,
      sha256:
          'e29d8041115f924c8fb0ad11c42034fa0f5d76cd974903b56816e06e73767974',
    ),
  ),
  OcrLanguage(
    'ara',
    native: 'العربية',
    english: 'Arabic',
    fast: (
      bytes: 1432056,
      sha256:
          'e3206d3dc87fd50c24a0fb9f01838615911d25168f4e64415244b67d2bb3e729',
    ),
    best: (
      bytes: 12603724,
      sha256:
          'ab9d157d8e38ca00e7e39c7d5363a5239e053f5b0dbdb3167dde9d8124335896',
    ),
  ),
  OcrLanguage(
    'asm',
    native: 'অসমীয়া',
    english: 'Assamese',
    fast: (
      bytes: 2045427,
      sha256:
          '299c7f6135ac72ca4820d4c39e3cf65b32b24127fc78c4938d11153adbb9fa77',
    ),
    best: (
      bytes: 11315350,
      sha256:
          '7ee579ad079e30566e856dfe7fc5ce0724f3625e69025cc88c785237172d9308',
    ),
  ),
  OcrLanguage(
    'aze',
    native: 'Azərbaycan',
    english: 'Azerbaijani',
    fast: (
      bytes: 3524799,
      sha256:
          'a365310848aecb739f19369cb3831d4660fcd9345d798e91a3042455f9ccc9f0',
    ),
    best: (
      bytes: 6281404,
      sha256:
          '6f183760f210177cf8c8eb6bf4821a8e488a4137ad06549ae483266c7cfd455f',
    ),
  ),
  OcrLanguage(
    'aze_cyrl',
    native: 'Азәрбајҹан',
    english: 'Azerbaijani (Cyrillic)',
    fast: (
      bytes: 1943672,
      sha256:
          '2e96ab67817819e14a3a2d6250261130457c8e78dde3077841ab391fe003551c',
    ),
    best: (
      bytes: 4700277,
      sha256:
          'e857ab208c63fe9286add2bea39846793bf80e5cf823b5a3853e35702e35b400',
    ),
  ),
  OcrLanguage(
    'bel',
    native: 'Беларуская',
    english: 'Belarusian',
    fast: (
      bytes: 3692098,
      sha256:
          '9c6668a0b202f3dcfe074b64620d108e1902ca7498a40b5a11b4a3da6112d58f',
    ),
    best: (
      bytes: 10870278,
      sha256:
          'f9503249d58dcfe794c3175abf4d21b1cb76c2dac891626fc864f217e0bb9294',
    ),
  ),
  OcrLanguage(
    'ben',
    native: 'বাংলা',
    english: 'Bengali',
    fast: (
      bytes: 855841,
      sha256:
          '31163084c279aaebd376216f0c3d5c17ad4b5fee8db49dae79c20000b5de5964',
    ),
    best: (
      bytes: 11045427,
      sha256:
          '1cd0129288d1f74f6661c35e638e487bd146a66bb732ecd9e011e48dcb0df623',
    ),
  ),
  OcrLanguage(
    'bod',
    native: 'བོད་ཡིག',
    english: 'Tibetan',
    fast: (
      bytes: 1966440,
      sha256:
          '1aab1db8dae337dfc8fa0f94a1c137c47e4c7857c3e6b30093ec726cef912a0b',
    ),
    best: (
      bytes: 8623846,
      sha256:
          '7b086e5d13fe9f04b873cfd0f71586717307cbbbe5eefb72a1d7a75d7fcf9da4',
    ),
  ),
  OcrLanguage(
    'bos',
    native: 'Bosanski',
    english: 'Bosnian',
    fast: (
      bytes: 2498242,
      sha256:
          '6cc8cc87cf1afbfa6a41febb725dbadb14bed96a46685906440a6eb8a7892f04',
    ),
    best: (
      bytes: 5264248,
      sha256:
          '009b938969013ce99793a8c90fa06ff2e5ce3fde8036d2790dc2e782829c06eb',
    ),
  ),
  OcrLanguage(
    'bre',
    native: 'Brezhoneg',
    english: 'Breton',
    fast: (
      bytes: 6335007,
      sha256:
          'db8b31f76b986d63b82dfff9e84e252bf5f7dc53d9128167aaab18b3ec96dd49',
    ),
    best: (
      bytes: 15640760,
      sha256:
          '18f11e71bafe0b6170531dd9910ed20ae72dc3750c335d15199ea51ccf029c27',
    ),
  ),
  OcrLanguage(
    'bul',
    native: 'Български',
    english: 'Bulgarian',
    fast: (
      bytes: 1675212,
      sha256:
          'aebc9b0fcc8cfaf8a9f38a02bb7b85052bd850744696a2c11cf0081820e5b21e',
    ),
    best: (
      bytes: 8844613,
      sha256:
          '87322f07ae023d0f61d3c12507f6f1ed22411c00f1b2e722d2e13b723584fad1',
    ),
  ),
  OcrLanguage(
    'cat',
    native: 'Català',
    english: 'Catalan',
    fast: (
      bytes: 1146012,
      sha256:
          '250db73cd5b380d2798581295dc12f20d0828cdb335a65d833d12dfdbf57117d',
    ),
    best: (
      bytes: 3802329,
      sha256:
          'dbddfce4cc65e5b127566d85243fe4422ef321f028b74ccf8db5c253f227a61a',
    ),
  ),
  OcrLanguage(
    'ceb',
    native: 'Cebuano',
    english: 'Cebuano',
    fast: (
      bytes: 716214,
      sha256:
          '346a39de801495c93ece6656d018d7d19d298af7db42d82ebae99dfe8ee14961',
    ),
    best: (
      bytes: 3452674,
      sha256:
          '3ae6bf43f11a5c6a1656f23d8c89adc8c0c641a2ae0a4963bbbbbb6e7b177eff',
    ),
  ),
  OcrLanguage(
    'ces',
    native: 'Čeština',
    english: 'Czech',
    fast: (
      bytes: 3795684,
      sha256:
          '934bcaf97ef3348413263331131c9fa7f55f30db333c711929c124fb635f7e1b',
    ),
    best: (
      bytes: 10918912,
      sha256:
          'd821773116d3c4e0360ea750066436c60ae45af02c39da3a840a543d761b3f41',
    ),
  ),
  OcrLanguage(
    'chi_sim',
    native: '简体中文',
    english: 'Chinese (Simplified)',
    fast: (
      bytes: 2469156,
      sha256:
          'a5fcb6f0db1e1d6d8522f39db4e848f05984669172e584e8d76b6b3141e1f730',
    ),
    best: (
      bytes: 13077423,
      sha256:
          '4fef2d1306c8e87616d4d3e4c6c67faf5d44be3342290cf8f2f0f6e3aa7e735b',
    ),
  ),
  OcrLanguage(
    'chi_sim_vert',
    native: '简体中文 (竖排)',
    english: 'Chinese (Simplified, vertical)',
    fast: (
      bytes: 1927902,
      sha256:
          '20590de84725bab69cde93bd6e8ed360a13cc5421a7e7364ddeb93e9af53d6da',
    ),
    best: (
      bytes: 13077507,
      sha256:
          'ea672a78157199c333aa12ec4e74550077689b545df5fc770903716850c8b2e5',
    ),
  ),
  OcrLanguage(
    'chi_tra',
    native: '繁體中文',
    english: 'Chinese (Traditional)',
    fast: (
      bytes: 2366642,
      sha256:
          '529c5b5797d64b126065cd55f2bb4c7fd7b15790798091b1ff259941a829330b',
    ),
    best: (
      bytes: 12985735,
      sha256:
          '1aa60488574cafa69486d919284f079ca9b68fcc7f6ad8dc1ff1b318dfd97028',
    ),
  ),
  OcrLanguage(
    'chi_tra_vert',
    native: '繁體中文 (直排)',
    english: 'Chinese (Traditional, vertical)',
    fast: (
      bytes: 1824756,
      sha256:
          '1df02a4b210e5c217b783819538b63e9dfe6904e2b5e53b62664f1b9f7a989d0',
    ),
    best: (
      bytes: 12985521,
      sha256:
          'bbe518f94b9e3852109113507357bfe7e257834d88d2d1ead44178046bcd2181',
    ),
  ),
  OcrLanguage(
    'chr',
    native: 'ᏣᎳᎩ',
    english: 'Cherokee',
    fast: (
      bytes: 374944,
      sha256:
          'a4da60d844ebb9dbaeb8843a92290083c1fd275b167fc9c9686d790ccd311fab',
    ),
    best: (
      bytes: 2258703,
      sha256:
          'b3a0da90e7744cfec534cdf2dd85860718f32b5595a07d4b7e49113a89bd0f98',
    ),
  ),
  OcrLanguage(
    'cos',
    native: 'Corsu',
    english: 'Corsican',
    fast: (
      bytes: 2299099,
      sha256:
          '018952d1b4b3d4fd6ee5ebbacf90603c9cef6221951359937c274fe1f190f8d3',
    ),
    best: (
      bytes: 8830216,
      sha256:
          'eb30628f7babafcb55286f9a181f80a5d20fab6dacd1fcde376fd9550f855659',
    ),
  ),
  OcrLanguage(
    'cym',
    native: 'Cymraeg',
    english: 'Welsh',
    fast: (
      bytes: 2208919,
      sha256:
          '7f6ee3374749645a7c92dfe773f5c3d6492194d371712ecfd775edc53c363fb4',
    ),
    best: (
      bytes: 8750784,
      sha256:
          '4f45069e33ef9719dab3417dfbcb9cebb87078bf95a614dcc038cf9d7ae1b580',
    ),
  ),
  OcrLanguage(
    'dan',
    native: 'Dansk',
    english: 'Danish',
    fast: (
      bytes: 2580059,
      sha256:
          'acb1fd074487a31d1294fcdfd7d7c673467ffd8aeacb2ccd61ebcbf04eb4e2fa',
    ),
    best: (
      bytes: 9758142,
      sha256:
          '28901bf4b58a657b511fddafce4ce245a1f21c5ee075734b479d01ab8d4cb6a5',
    ),
  ),
  OcrLanguage(
    'deu',
    native: 'Deutsch',
    english: 'German',
    fast: (
      bytes: 1525436,
      sha256:
          '19d219bbb6672c869d20a9636c6816a81eb9a71796cb93ebe0cb1530e2cdb22d',
    ),
    best: (
      bytes: 8628461,
      sha256:
          '8407331d6aa0229dc927685c01a7938fc5a641d1a9524f74838cdac599f0d06e',
    ),
  ),
  OcrLanguage(
    'deu_latf',
    native: 'Deutsch (Fraktur)',
    english: 'German (Fraktur)',
    fast: (
      bytes: 6423052,
      sha256:
          '7cd1b541e9d3884b9546a7d292c4f349cdb45ff646b4b43166dfc5099a8ad1a1',
    ),
    best: (
      bytes: 12938047,
      sha256:
          '429b8c33d37e1a4823a2bb082a644ff13e252f735b7945e08a518d22ddcc459e',
    ),
  ),
  OcrLanguage(
    'div',
    native: 'ދިވެހި',
    english: 'Dhivehi',
    fast: (
      bytes: 1774535,
      sha256:
          '06051412588963b34b663cc59a468dbf10753329f015ccd574ee711e8c6b84c3',
    ),
    best: (
      bytes: 4574116,
      sha256:
          '7f923088b173b278ed9d27609fccc9b6571ef7dae11898825d934ed6a2998133',
    ),
  ),
  OcrLanguage(
    'dzo',
    native: 'རྫོང་ཁ',
    english: 'Dzongkha',
    fast: (
      bytes: 449596,
      sha256:
          '364d244fad3f8d4438c9f7ee7642b9b876a4620cf76c0115619b979d6bfef1fa',
    ),
    best: (
      bytes: 3243805,
      sha256:
          '7587d0ee3161ec8a4d939482207eba94fb81ab3c2d80f2b4c4a2c429b8d8b99a',
    ),
  ),
  OcrLanguage(
    'ell',
    native: 'Ελληνικά',
    english: 'Greek',
    fast: (
      bytes: 1419514,
      sha256:
          '4fba8a0b461038d51f1c20d043d4f2ac38c4e778f1b90830847f7bd8fa3ba726',
    ),
    best: (
      bytes: 8945021,
      sha256:
          '288b4ea00bab450cf39893d22f04a2835a8469b673b5b20dcb39b159d1bbc9b8',
    ),
  ),
  OcrLanguage(
    'eng',
    native: 'English',
    english: 'English',
    fast: (
      bytes: 4113088,
      sha256:
          '7d4322bd2a7749724879683fc3912cb542f19906c83bcc1a52132556427170b2',
    ),
    best: (
      bytes: 15400601,
      sha256:
          '8280aed0782fe27257a68ea10fe7ef324ca0f8d85bd2fd145d1c2b560bcb66ba',
    ),
  ),
  OcrLanguage(
    'enm',
    native: 'Middle English',
    english: 'Middle English',
    fast: (
      bytes: 3101551,
      sha256:
          'd312ab5aafc9f99a78082c75e035b0873d2da6cb6d95cde03e219c1b26750034',
    ),
    best: (
      bytes: 13281564,
      sha256:
          '934463c845bdf9bfe087038f96a3b1b770d8e5fd6175ef0892066a02b2bd0e52',
    ),
  ),
  OcrLanguage(
    'epo',
    native: 'Esperanto',
    english: 'Esperanto',
    fast: (
      bytes: 4728393,
      sha256:
          '71181a6a07af3812aeedfa1aa993623424f4b8a6aac3e271b36ec11774e674d9',
    ),
    best: (
      bytes: 7402169,
      sha256:
          '43b6b859a59e26b5787962e100fdd16999b2af918f10ca62bcc3f7d2f9744365',
    ),
  ),
  OcrLanguage(
    'est',
    native: 'Eesti',
    english: 'Estonian',
    fast: (
      bytes: 4458101,
      sha256:
          '515d4a773682b286369511e83fe412bcff16a92a886f99c761c1d760a7e30456',
    ),
    best: (
      bytes: 15833749,
      sha256:
          'd7bfea95a53c302b378655314adc366e294a5a95d7d611911fce5e66318d3ccd',
    ),
  ),
  OcrLanguage(
    'eus',
    native: 'Euskara',
    english: 'Basque',
    fast: (
      bytes: 5175921,
      sha256:
          '40e7418296c355d9fd9ca843d115c51e740089e576e887443e61704823cd6624',
    ),
    best: (
      bytes: 7933869,
      sha256:
          'cd2d5452b6cc704924e5a0a31667dc5cb9f16d4e5cf7cb0629af3781086af7dd',
    ),
  ),
  OcrLanguage(
    'fao',
    native: 'Føroyskt',
    english: 'Faroese',
    fast: (
      bytes: 3439772,
      sha256:
          '0ed46203c283c952b7de0530d1c6e6ac9a25a79773fb89cadd149275ffea9a80',
    ),
    best: (
      bytes: 10030003,
      sha256:
          '7e4f7a4ac23e6379aad2d4aacdf11e1875cd88e35ffc11eb78005e0e470ce962',
    ),
  ),
  OcrLanguage(
    'fas',
    native: 'فارسی',
    english: 'Persian',
    fast: (
      bytes: 431500,
      sha256:
          'db1c0a91208aff00d3cf1ed2c1d23f76419afd5f024688b4f71adc3f2ce4a505',
    ),
    best: (
      bytes: 3325955,
      sha256:
          '99e420969b5ddd2cb135b416316a7ed417c59c4faf9e0d28941348f6448114df',
    ),
  ),
  OcrLanguage(
    'fil',
    native: 'Filipino',
    english: 'Filipino',
    fast: (
      bytes: 1841715,
      sha256:
          '2b17f68014ab44b88b5e2334ebcd0ce0090d9af7c6fbef6fab22e0bbd9a934dd',
    ),
    best: (
      bytes: 8978743,
      sha256:
          '04a7d20dcd2e1869375cbf47b59d8ed4ceea98c7f01706269eced3945b763647',
    ),
  ),
  OcrLanguage(
    'fin',
    native: 'Suomi',
    english: 'Finnish',
    fast: (
      bytes: 7865732,
      sha256:
          '61a04cd62b507c3d9ae0e1cda399e6715ebf49dea9df47897c8acdcd3bd3e13c',
    ),
    best: (
      bytes: 14369979,
      sha256:
          '96745dd0900fe997541516863d859616df6120430db546424feae72923828423',
    ),
  ),
  OcrLanguage(
    'fra',
    native: 'Français',
    english: 'French',
    fast: (
      bytes: 1130365,
      sha256:
          'ced037562e8c80c13122dece28dd477d399af80911a28791a66a63ac1e3445ca',
    ),
    best: (
      bytes: 3972885,
      sha256:
          '907743d98915c91a3906dfbf6e48b97598346698fe53aaa797e1a064ffcac913',
    ),
  ),
  OcrLanguage(
    'frm',
    native: 'Moyen français',
    english: 'Middle French',
    fast: (
      bytes: 2024948,
      sha256:
          '3fe6eed7108136a85dbbf53baf23d9fb435afe1262323f5fba7711b6c6048728',
    ),
    best: (
      bytes: 4043005,
      sha256:
          '72c2de7476d9800a4a12c3d1b9e8c3c211fb76ff9793f4cf453bba8d0672eb77',
    ),
  ),
  OcrLanguage(
    'fry',
    native: 'Frysk',
    english: 'Western Frisian',
    fast: (
      bytes: 1906018,
      sha256:
          '7c9dbc47ef3848e33b623d1b927dd4d998ed39ff750fbc0f14aeb0f627b5da15',
    ),
    best: (
      bytes: 8442509,
      sha256:
          'da42beb26f975f83c3436f2b5fd4132c9f9c3064fbeffb49ba3870b00fcf8db9',
    ),
  ),
  OcrLanguage(
    'gla',
    native: 'Gàidhlig',
    english: 'Scottish Gaelic',
    fast: (
      bytes: 3068307,
      sha256:
          'cb7b206d9f56b601d1666683ea8a516c8bb9c04362dbb874fc9665b339b72adf',
    ),
    best: (
      bytes: 9599424,
      sha256:
          'b0c35f0b10ff45735d2c488c8cab8fb6fc56631c8a7e38f8210e1dff05b34f8d',
    ),
  ),
  OcrLanguage(
    'gle',
    native: 'Gaeilge',
    english: 'Irish',
    fast: (
      bytes: 1181824,
      sha256:
          '2fe9ba6119aac7e2a20d6cfb69ed91afe9520f41bc7e3a903f84280f2663858d',
    ),
    best: (
      bytes: 3942458,
      sha256:
          'f8e198fb8243be9b167fe49c90794bf5ed3c239e67a79de5e22306e43b0aaa55',
    ),
  ),
  OcrLanguage(
    'glg',
    native: 'Galego',
    english: 'Galician',
    fast: (
      bytes: 2554555,
      sha256:
          '7947619c5544d86849f563bd737ad90dbea9f5319fbd838c4747a7a1cd40b260',
    ),
    best: (
      bytes: 12709487,
      sha256:
          'bfe93fafb41a44e9efd612c6f9833f8a7f76a157824d933420116f5aa3439463',
    ),
  ),
  OcrLanguage(
    'grc',
    native: 'Ἀρχαία ἑλληνικά',
    english: 'Greek, Ancient',
    fast: (
      bytes: 2246328,
      sha256:
          '57b735557eeb67503803cf9f99786dd0b62417931352601952a0b1a23b6c4759',
    ),
    best: (
      bytes: 5168122,
      sha256:
          'dfc9bda286cd9d8755b1832e5731a5425d1cf0803393a5fa6dee078466178cf1',
    ),
  ),
  OcrLanguage(
    'guj',
    native: 'ગુજરાતી',
    english: 'Gujarati',
    fast: (
      bytes: 1418394,
      sha256:
          'fa69658614b4946a9afae8853d67e0689838803dfa3d12c2e35ec53ee6f8df34',
    ),
    best: (
      bytes: 8515761,
      sha256:
          '8cbb1d139b63434b9e1154a3b51930a74ec1c9a6251b95d86d74d7f1cd706ed6',
    ),
  ),
  OcrLanguage(
    'hat',
    native: 'Kreyòl ayisyen',
    english: 'Haitian Creole',
    fast: (
      bytes: 1976902,
      sha256:
          '842e489a0e0eb12c72b5cb12e9e6624aae5928de1d097d76445474c263ce8b5a',
    ),
    best: (
      bytes: 12128251,
      sha256:
          '37a2d94a952649da9c8bd18ed3ab4e7c91250656027751f6ccf75a3d8b7457e8',
    ),
  ),
  OcrLanguage(
    'heb',
    native: 'עברית',
    english: 'Hebrew',
    fast: (
      bytes: 961404,
      sha256:
          '11f9e43ab227f786352a50f75c94c2e9906f1baba86d93276da19da7ce0904db',
    ),
    best: (
      bytes: 3704077,
      sha256:
          'dbaa827aea6bc21215638447f17783a1004987c2d0bf5573d111fee397abdae5',
    ),
  ),
  OcrLanguage(
    'hin',
    native: 'हिन्दी',
    english: 'Hindi',
    fast: (
      bytes: 1122751,
      sha256:
          '4c73ffc59d497c186b19d1e90f5d721d678ea6b2e277b719bee4e2af12271825',
    ),
    best: (
      bytes: 11895564,
      sha256:
          'bd2e65a2184af08a167b0be2439e91fa5edbc4394399ca2f692b843ae26e78d6',
    ),
  ),
  OcrLanguage(
    'hrv',
    native: 'Hrvatski',
    english: 'Croatian',
    fast: (
      bytes: 4103348,
      sha256:
          '9e515d9832ce259dbab550b1cc6b998f8b929faf2edacaaca981b05adb130571',
    ),
    best: (
      bytes: 11195424,
      sha256:
          'a46566f0a1442502028bc0c35f043bc1780cc80e8567ec1b1df13d685c47215e',
    ),
  ),
  OcrLanguage(
    'hun',
    native: 'Magyar',
    english: 'Hungarian',
    fast: (
      bytes: 5296273,
      sha256:
          '35067e7cfe102dcdc953f9a758fdfaa6296b17a1ee6d874ee780fa306430b9fb',
    ),
    best: (
      bytes: 12350405,
      sha256:
          '08786ad5fe25d502d1cfcdf606ba215f320409a1630109582fa1a38d93b3e32d',
    ),
  ),
  OcrLanguage(
    'hye',
    native: 'Հայերեն',
    english: 'Armenian',
    fast: (
      bytes: 3463717,
      sha256:
          'b701d0d95799a716143dedb0197504e56f27a1bb133d6607ff5778c6988cb67c',
    ),
    best: (
      bytes: 6372242,
      sha256:
          'ca46afdca95b5436e9510fd2fc59aff45c306132433a4267eed2bd422cdd29f4',
    ),
  ),
  OcrLanguage(
    'iku',
    native: 'ᐃᓄᒃᑎᑐᑦ',
    english: 'Inuktitut',
    fast: (
      bytes: 2802266,
      sha256:
          '81ef16ee0fa0a3548c8a2d1ff10786e3278b6720e51cefd9a81a506f52660223',
    ),
    best: (
      bytes: 6139484,
      sha256:
          '6b65466ef44f8d38e593ecfedaf0434cc24163c108db1a019c68ac174e035905',
    ),
  ),
  OcrLanguage(
    'ind',
    native: 'Bahasa Indonesia',
    english: 'Indonesian',
    fast: (
      bytes: 1122661,
      sha256:
          '69786901da87ab8766c1ea7fbb10b28f2110c14da3f6c8f2735df131fba95d88',
    ),
    best: (
      bytes: 8253606,
      sha256:
          '1f6596041ffb4cd5094e5f98764db43cfde04edb8f02b988f90ebc1353ac73b8',
    ),
  ),
  OcrLanguage(
    'isl',
    native: 'Íslenska',
    english: 'Icelandic',
    fast: (
      bytes: 2278973,
      sha256:
          '5ec828c363f3f0062c3caf08216677cf5f3c0c981b05fab445123a16b98f10a9',
    ),
    best: (
      bytes: 9486436,
      sha256:
          'b4bf195ce73fa9098ccdf7b8b25ffb7cfb1395346bb3fa1355c40d4bc9e6792a',
    ),
  ),
  OcrLanguage(
    'ita',
    native: 'Italiano',
    english: 'Italian',
    fast: (
      bytes: 2701314,
      sha256:
          'b8f89e1e785118dac4d51ae042c029a64edb5c3ee42ef73027a6d412748d8827',
    ),
    best: (
      bytes: 8863635,
      sha256:
          '8df9c89176fb93f56bf4b2d4ede04c01c1f31d4b7697fbd76cc336df700f3f38',
    ),
  ),
  OcrLanguage(
    'ita_old',
    native: 'Italiano antico',
    english: 'Italian (old)',
    fast: (
      bytes: 3286123,
      sha256:
          'ee85de25acf70d5eeefdb3012424814a18ab368183099cc2c3f2fe2d3dce3b02',
    ),
    best: (
      bytes: 9852171,
      sha256:
          '6bba512704bc5417462435f7c98f6b2be86457d544bbb09c7f9ab5caef955b5d',
    ),
  ),
  OcrLanguage(
    'jav',
    native: 'Basa Jawa',
    english: 'Javanese',
    fast: (
      bytes: 2982741,
      sha256:
          '46107b6bed3bf2d9617e5e192e52524e368242543fead1a7175c363dddd400f2',
    ),
    best: (
      bytes: 8650382,
      sha256:
          '914fe51f967efa4f05b72a852b2c234af3cdd4aefc0f64d43e39903d2108017a',
    ),
  ),
  OcrLanguage(
    'jpn',
    native: '日本語',
    english: 'Japanese',
    fast: (
      bytes: 2471260,
      sha256:
          '1f5de9236d2e85f5fdf4b3c500f2d4926f8d9449f28f5394472d9e8d83b91b4d',
    ),
    best: (
      bytes: 14330109,
      sha256:
          '36bdf9ac823f5911e624c30d0553e890b8abc7c31a65b3ef14da943658c40b79',
    ),
  ),
  OcrLanguage(
    'jpn_vert',
    native: '日本語 (縦書き)',
    english: 'Japanese (vertical)',
    fast: (
      bytes: 3037480,
      sha256:
          'bf1e2640954691797e2dc14f38533e601b59ee37958698ae0f0b81dc6f09c71b',
    ),
    best: (
      bytes: 14330809,
      sha256:
          '1258be6eb2a9851f18043234ad18cca13ed32690bfff62b335c898bbea371548',
    ),
  ),
  OcrLanguage(
    'kan',
    native: 'ಕನ್ನಡ',
    english: 'Kannada',
    fast: (
      bytes: 3608331,
      sha256:
          'bd31e6b6ae93271e3bcf5383d306d8eefbb91542937cd6d735a5930c970e61d8',
    ),
    best: (
      bytes: 10233763,
      sha256:
          '6f195e0f33f0ec5118c97eff777ed70ac453d67c32bf06a43f79dab875f8ebfe',
    ),
  ),
  OcrLanguage(
    'kat',
    native: 'ქართული',
    english: 'Georgian',
    fast: (
      bytes: 2524769,
      sha256:
          '557abb6f1c68bc1b286f1bdd00bb6b82f85a427a91899807dab6c2f6c7986731',
    ),
    best: (
      bytes: 4487336,
      sha256:
          '557f48b753fdbbee2c77d83bae2542af249f915be6cf80883892a579ea2a81db',
    ),
  ),
  OcrLanguage(
    'kat_old',
    native: 'ძველი ქართული',
    english: 'Georgian (old)',
    fast: (
      bytes: 423167,
      sha256:
          '7b77290303d5d88db6adc5b679d1eb876e3c62f64c8999e919bcb4608af379bc',
    ),
    best: (
      bytes: 3174400,
      sha256:
          'ada8c6b31828d2e208312e6d28b92fd94cb924f48f676506d3592cf023bb487d',
    ),
  ),
  OcrLanguage(
    'kaz',
    native: 'Қазақ',
    english: 'Kazakh',
    fast: (
      bytes: 4734644,
      sha256:
          'fcc01eed3815a42b9c6321c4c9d3606f39b166cbf95ade98b7d8d12063eae53d',
    ),
    best: (
      bytes: 7528853,
      sha256:
          '34cbd9204b1ff3cc813d50b29e3c0ae3752bcc201f261a4a393ceca3895aea9d',
    ),
  ),
  OcrLanguage(
    'khm',
    native: 'ខ្មែរ',
    english: 'Khmer',
    fast: (
      bytes: 1446926,
      sha256:
          '47f110575341b322052f3becbefee61a3ecf1ef549352b5d4d33d28afe30d099',
    ),
    best: (
      bytes: 8104332,
      sha256:
          '3d2d975e67a319bf1cd67626b12fdebc1e417a4ebef9c9afee01d9927b512815',
    ),
  ),
  OcrLanguage(
    'kir',
    native: 'Кыргызча',
    english: 'Kyrgyz',
    fast: (
      bytes: 9928497,
      sha256:
          '9777956300900b528d26932cf80693f95e75143433fb851d567194bcc38a31ae',
    ),
    best: (
      bytes: 11948344,
      sha256:
          '607cbaa07305217518df0e9c7334239000a8542689baefb3754e0aee15ae6a5c',
    ),
  ),
  OcrLanguage(
    'kmr',
    native: 'Kurmancî',
    english: 'Kurmanji (Northern Kurdish)',
    fast: (
      bytes: 3568615,
      sha256:
          'a3ef2daa828399ca8d6ae69edfa21ed21aa5abb3f868e2024d3235406312e7b6',
    ),
    best: (
      bytes: 10196464,
      sha256:
          '6017f6284e6771419f85a72218a2e84c5c6c19a4ed0ef27286cd637981293b76',
    ),
  ),
  OcrLanguage(
    'kor',
    native: '한국어',
    english: 'Korean',
    fast: (
      bytes: 1677415,
      sha256:
          '6b85e11d9bbf07863b97b3523b1b112844c43e713df8b66418a081fd1060b3b2',
    ),
    best: (
      bytes: 12528128,
      sha256:
          'f888d4038348a0c3d25151e7f452bda0d74ca275b18cab146798bcbb94084fff',
    ),
  ),
  OcrLanguage(
    'kor_vert',
    native: '한국어 (세로쓰기)',
    english: 'Korean (vertical)',
    fast: (
      bytes: 1113715,
      sha256:
          'c28f19dee36927baba5215fb793a3c00fff3ef2cfbcaa100122401d8f4374869',
    ),
    best: (
      bytes: 3964469,
      sha256:
          'e6c72327617c0bf195a9a8b631827bf102c75735bbb932126e6fa1c4656c7568',
    ),
  ),
  OcrLanguage(
    'lao',
    native: 'ລາວ',
    english: 'Lao',
    fast: (
      bytes: 6386744,
      sha256:
          '20124962e93e68121e02c49a949d1f9df5db87dd62e5e4aa578362ca532444f8',
    ),
    best: (
      bytes: 13532551,
      sha256:
          '12680f24af571909d69f0dd0151ecdf657a98f000c0ca011c11f8f9dc2bf69b7',
    ),
  ),
  OcrLanguage(
    'lat',
    native: 'Latina',
    english: 'Latin',
    fast: (
      bytes: 3187463,
      sha256:
          '3859d8ba60404f4b79830622625bbc76fb4ee2808eac1ad360ffa77f0a533328',
    ),
    best: (
      bytes: 9705145,
      sha256:
          '60054dd32ac03ebd9b4f87d0665bd491a7ffe0d3ee99ceb91aefaf348b65e94f',
    ),
  ),
  OcrLanguage(
    'lav',
    native: 'Latviešu',
    english: 'Latvian',
    fast: (
      bytes: 2717247,
      sha256:
          '7d9eaf22254b381f18b806cd6cb647862a397a7221adbce3e22cc421793a8847',
    ),
    best: (
      bytes: 5623473,
      sha256:
          'fc5b602bc21987e09468f9ec5baaef1d1a29e26eb334545531294a0af9407c69',
    ),
  ),
  OcrLanguage(
    'lit',
    native: 'Lietuvių',
    english: 'Lithuanian',
    fast: (
      bytes: 3154896,
      sha256:
          '1e383df5b055583bc01cb5764ecdf74c540753f2cb3f8205e7105361da4bc989',
    ),
    best: (
      bytes: 10252680,
      sha256:
          '7d47a118f60509408e1dae2dd967d7c553a770e57390fedf8e7af07a192fefe3',
    ),
  ),
  OcrLanguage(
    'ltz',
    native: 'Lëtzebuergesch',
    english: 'Luxembourgish',
    fast: (
      bytes: 2606426,
      sha256:
          '5516a78efa30c050da7eb0727fec3de59670c19735c00678a67fdad98e4b3ec1',
    ),
    best: (
      bytes: 12721945,
      sha256:
          'cc62ddc05eaa70e1ff0135a428b1ef553f3abd2e5f4485ca084a1980e251a3e1',
    ),
  ),
  OcrLanguage(
    'mal',
    native: 'മലയാളം',
    english: 'Malayalam',
    fast: (
      bytes: 5275996,
      sha256:
          'bd05cbf1b197e7810d2903419aedb06f9ef77bfedf50b358673c1d18d707cdb4',
    ),
    best: (
      bytes: 12524967,
      sha256:
          'b4a8b1b2fd8c5754aa0f543568626aad514d94a6c1e138ef0bf1a329aa189ef0',
    ),
  ),
  OcrLanguage(
    'mar',
    native: 'मराठी',
    english: 'Marathi',
    fast: (
      bytes: 2118233,
      sha256:
          '0ba3f2d116972e72fe9e176bc84c38e81dfb6670f4ed1f7f6c8e16a27da7cb61',
    ),
    best: (
      bytes: 13437670,
      sha256:
          '799405456528ffd688bc8173ea9179c0646120436ac35099dccb175c4c70f652',
    ),
  ),
  OcrLanguage(
    'mkd',
    native: 'Македонски',
    english: 'Macedonian',
    fast: (
      bytes: 1600188,
      sha256:
          '58622bf154830fa62103359938564aeb8112b929759e22a48224f3ecfaac34c6',
    ),
    best: (
      bytes: 3453054,
      sha256:
          'be5f0af7a7b7a1a804069bcab83225286d78ce3171c6a1d1587f975b083af299',
    ),
  ),
  OcrLanguage(
    'mlt',
    native: 'Malti',
    english: 'Maltese',
    fast: (
      bytes: 2308796,
      sha256:
          '3040b443d5d49e4183da0eaaf58d1033c3a616153d35d2342a56777f9bbb31c7',
    ),
    best: (
      bytes: 5060029,
      sha256:
          '0408941b9368de0009c530b68f0adc4735d6c26bfa02e549d0ee48afc776f0a4',
    ),
  ),
  OcrLanguage(
    'mon',
    native: 'Монгол',
    english: 'Mongolian',
    fast: (
      bytes: 2137042,
      sha256:
          'a151a3806d61ac43619cd383896d551ba5c3b07388ffec6fc83c8c604d677570',
    ),
    best: (
      bytes: 8646663,
      sha256:
          '186dcb2ef79e0dc1ab88da2231926d79070c20176bf7416a19389331f68faf65',
    ),
  ),
  OcrLanguage(
    'mri',
    native: 'Māori',
    english: 'Maori',
    fast: (
      bytes: 862973,
      sha256:
          '8552be985e8fa0210d6d815d736151d645089b590a56f2d92391fb864e8bf9c9',
    ),
    best: (
      bytes: 3610177,
      sha256:
          '67d322dcc41ca59929236c85393c6ecc644c29feda149fbe2b95adcb4a1b0494',
    ),
  ),
  OcrLanguage(
    'msa',
    native: 'Bahasa Melayu',
    english: 'Malay',
    fast: (
      bytes: 1747801,
      sha256:
          'e41a3e5febfec50c90371eb1cbb17a48b10cad387900e3420b1f134c1b766cba',
    ),
    best: (
      bytes: 8230552,
      sha256:
          '2fa693701d2fb3685cf3e0a64bc1bfb97d66a50f93c07b2ebc0ff360ea62621f',
    ),
  ),
  OcrLanguage(
    'mya',
    native: 'မြန်မာ',
    english: 'Burmese',
    fast: (
      bytes: 4640561,
      sha256:
          '02aa6c25cfe9e583fa7b5d4131eac948f962308983f0f397df077dea58212b03',
    ),
    best: (
      bytes: 14971060,
      sha256:
          '629dc3ab7adf4321f329d99f8c737d920308df7519734e36277b773c24df0699',
    ),
  ),
  OcrLanguage(
    'nep',
    native: 'नेपाली',
    english: 'Nepali',
    fast: (
      bytes: 1002911,
      sha256:
          '280ba9450b4f21afbf5985e0de87857b75a972577c50ef0603c141ddde4f1cb8',
    ),
    best: (
      bytes: 12387399,
      sha256:
          '54907633d05bb9fae7dbfb3d8a61ddf2f579127375aa53b8afc657efb34a79f0',
    ),
  ),
  OcrLanguage(
    'nld',
    native: 'Nederlands',
    english: 'Dutch',
    fast: (
      bytes: 6050296,
      sha256:
          'ced0e5e046a84c908a6aa7accbef9a232c4a5d9a8276691b81c6ee64d02963f6',
    ),
    best: (
      bytes: 8903736,
      sha256:
          '92e7a1ad4bf8082e268de57c7823316ec024935702c6ed2a1e473b3a071aa733',
    ),
  ),
  OcrLanguage(
    'nor',
    native: 'Norsk',
    english: 'Norwegian',
    fast: (
      bytes: 3610079,
      sha256:
          '0451eb4f8049ae78196806bf878a389a2f40f1386fe038568cf4441226ba6ef2',
    ),
    best: (
      bytes: 14312333,
      sha256:
          '451d52ba1559aa1aecf163ccbfdeced2b9605fbd49480f5e8a53ace29b9eb0e7',
    ),
  ),
  OcrLanguage(
    'oci',
    native: 'Occitan',
    english: 'Occitan',
    fast: (
      bytes: 6322087,
      sha256:
          '747b9be4c5b80b4c730ce4f426a3b85060a1bb0de54cd566fcbdcb7f407940c9',
    ),
    best: (
      bytes: 12917692,
      sha256:
          '623733a34bb8923e8806701d324c6c021f949debf233fe98bfd58f9b6939fe2d',
    ),
  ),
  OcrLanguage(
    'ori',
    native: 'ଓଡ଼ିଆ',
    english: 'Odia',
    fast: (
      bytes: 1480066,
      sha256:
          '36f3135e61d501a3acfad41f5fe60b8e791274fff4c5375c969fdcca980cdbac',
    ),
    best: (
      bytes: 8110602,
      sha256:
          '90dfe91cea0b25cf96b2bb283905ba1452534776df3f00d47530939d56339534',
    ),
  ),
  OcrLanguage(
    'pan',
    native: 'ਪੰਜਾਬੀ',
    english: 'Punjabi',
    fast: (
      bytes: 497721,
      sha256:
          '1ec0907fc3534065ea9ae190c6bb7ec9e5c74fd9d2fa996aaec7407f11ad8131',
    ),
    best: (
      bytes: 11893154,
      sha256:
          '6971b1f5c4094da3d73cd13bc79429de912a31919330324556a26e3b4802b905',
    ),
  ),
  OcrLanguage(
    'pol',
    native: 'Polski',
    english: 'Polish',
    fast: (
      bytes: 4765518,
      sha256:
          'c4476cdbc0e33d898d32345122b7be1cbf85ace15f920f06c7714756e1ef79b2',
    ),
    best: (
      bytes: 11978867,
      sha256:
          'e80cc4cefbdface06e9223f43f089556b9dcf104020fbc0a200f6863c57d4405',
    ),
  ),
  OcrLanguage(
    'por',
    native: 'Português',
    english: 'Portuguese',
    fast: (
      bytes: 1982756,
      sha256:
          'c4932b937207a9514b7514d518b931a99938c02a28a5a5a553f8599ed58b7deb',
    ),
    best: (
      bytes: 8159939,
      sha256:
          '711de9dbb8052067bd42f16b9119967f30bada80d57e2ef24f65d09f531adb04',
    ),
  ),
  OcrLanguage(
    'pus',
    native: 'پښتو',
    english: 'Pashto',
    fast: (
      bytes: 1772087,
      sha256:
          'f15550bfe3a20ca781cf5afb7b2af6ee769c6521cf4bb990848e72856b484600',
    ),
    best: (
      bytes: 11987930,
      sha256:
          'b5e3ad39342e1b8cedf3b74cb647eeb0858fec74c00aa98703288aef01ebad65',
    ),
  ),
  OcrLanguage(
    'que',
    native: 'Runasimi',
    english: 'Quechua',
    fast: (
      bytes: 5026336,
      sha256:
          '9a3f78b010254ae237a7ca89e65e6d0c349221e437ac1575df1877e63a76bf57',
    ),
    best: (
      bytes: 10774587,
      sha256:
          'fe8872e0360ecedd40c9df8585fa853a2d82b99a8daa454892ddf9db12fe9135',
    ),
  ),
  OcrLanguage(
    'ron',
    native: 'Română',
    english: 'Romanian',
    fast: (
      bytes: 2376323,
      sha256:
          '9adfde6b51ba4b97efd10ea37c3070fd3fc2bad7815e81f5c3c198cd96216cc9',
    ),
    best: (
      bytes: 9595755,
      sha256:
          '93588d7e59a28fad7920db07767345438ee5eeefa3c5f20541dfb9ad083a6d2e',
    ),
  ),
  OcrLanguage(
    'rus',
    native: 'Русский',
    english: 'Russian',
    fast: (
      bytes: 3861738,
      sha256:
          'e16e5e036cce1d9ec2b00063cf8b54472625b9e14d893a169e2b0dedeb4df225',
    ),
    best: (
      bytes: 15301764,
      sha256:
          'b617eb6830ffabaaa795dd87ea7fd251adfe9cf0efe05eb9a2e8128b7728d6b6',
    ),
  ),
  OcrLanguage(
    'san',
    native: 'संस्कृतम्',
    english: 'Sanskrit',
    fast: (
      bytes: 12404677,
      sha256:
          'a399958921c64e7d2319369ade1e74b4db2577744ac5bfeabd16663cf743b91c',
    ),
    best: (
      bytes: 15136202,
      sha256:
          '5fbc152e7946b3b8201a2a557864bd23b521db4102b521f3e95169c82c5d0b0d',
    ),
  ),
  OcrLanguage(
    'sin',
    native: 'සිංහල',
    english: 'Sinhala',
    fast: (
      bytes: 1727413,
      sha256:
          'bc75c6df2375a30c9f7e759fa7d4b58ae3ecf9ce72668a702d01acb13e551422',
    ),
    best: (
      bytes: 8282713,
      sha256:
          '1d95b36e935c8c12cc890684fad15bd3ad8d904c3a6ffa2fccb81658eabd8454',
    ),
  ),
  OcrLanguage(
    'slk',
    native: 'Slovenčina',
    english: 'Slovak',
    fast: (
      bytes: 4427661,
      sha256:
          'fbcc400a9c74c6a13d922fcb1211b655d1b165387b675ed75cd2dbd756b974a5',
    ),
    best: (
      bytes: 11542252,
      sha256:
          '3553e335f64408412c8741fec19e443b5fda81d88abe59aa1401cba4e8825bed',
    ),
  ),
  OcrLanguage(
    'slv',
    native: 'Slovenščina',
    english: 'Slovenian',
    fast: (
      bytes: 3003829,
      sha256:
          'b937632c17ce5fdf20535d25feec044da10a0c4c8234f4302d5606fd671cf60d',
    ),
    best: (
      bytes: 5879151,
      sha256:
          '199c39cc570812db5011ad7e8552c04b0784413043a8e4561d85c8ac364fba5c',
    ),
  ),
  OcrLanguage(
    'snd',
    native: 'سنڌي',
    english: 'Sindhi',
    fast: (
      bytes: 1694035,
      sha256:
          'f25cae3b325b0a6dc4dd5d8aeb3ac40b129a18bdd92666317022ee198f7878a7',
    ),
    best: (
      bytes: 11981538,
      sha256:
          'd945fc2f379b6c353bf28bf06d545a9270f6a7d11c05c0c0fb20ed29650ba2e3',
    ),
  ),
  OcrLanguage(
    'spa',
    native: 'Español',
    english: 'Spanish',
    fast: (
      bytes: 2294433,
      sha256:
          '6f2e04d02774a18f01bed44b1111f2cd7f3ba7ac9dc4373cd3f898a40ea6b464',
    ),
    best: (
      bytes: 13570187,
      sha256:
          'e2c1ffdad8b30f26c45d4017a9183d3a7f9aa69e59918be4f88b126fac99ab2c',
    ),
  ),
  OcrLanguage(
    'spa_old',
    native: 'Español antiguo',
    english: 'Spanish (old)',
    fast: (
      bytes: 2894755,
      sha256:
          '11d89a6763ff134ef8f7e41b995974d36fba5d1a807156d3202d7bf991bb1823',
    ),
    best: (
      bytes: 9476925,
      sha256:
          '82eda2ae145ce6560e34f8b7b037707bbd7dca109151a50e3356e2fa2ae635e8',
    ),
  ),
  OcrLanguage(
    'sqi',
    native: 'Shqip',
    english: 'Albanian',
    fast: (
      bytes: 1874705,
      sha256:
          '1d89621d9afe8ddf35b403ecf8951edea52c3a960d241f287b1a7b2c5ba8daac',
    ),
    best: (
      bytes: 4631498,
      sha256:
          '42fa3ff84e1684b8989423d53c9f7d4fb8adaa65a54a3d87f9d259228d01226c',
    ),
  ),
  OcrLanguage(
    'srp',
    native: 'Српски',
    english: 'Serbian',
    fast: (
      bytes: 2149931,
      sha256:
          'aa41ae3d9cc705e60d398ab38a5c3cc8b772c0d420c7d4f0859beb13d0e321b6',
    ),
    best: (
      bytes: 9345851,
      sha256:
          'b090f9bb22366d9b4b0cb6baa2136c4f75e992ddba01ecb78240896e359e4072',
    ),
  ),
  OcrLanguage(
    'srp_latn',
    native: 'Srpski (latinica)',
    english: 'Serbian (Latin)',
    fast: (
      bytes: 3281787,
      sha256:
          '54b2e001bd8a336bdffc249c1487b8b7cb712f0a031f2551930ba050ebefa2a0',
    ),
    best: (
      bytes: 9831713,
      sha256:
          '9bc6caa2ad9daf1706bf4c21741992dd5a334e9ff64cfc1ecd32aa43dd7a150c',
    ),
  ),
  OcrLanguage(
    'sun',
    native: 'Basa Sunda',
    english: 'Sundanese',
    fast: (
      bytes: 1369500,
      sha256:
          'fa939213b005b3477a1032b7222f63cd0b0ac486f83fd9554caf653d6e6c6ffe',
    ),
    best: (
      bytes: 4132820,
      sha256:
          'a9fc58f3868c7e88c4791078090a7f7436b01cc45cd660f7b756a0e0683b5a5c',
    ),
  ),
  OcrLanguage(
    'swa',
    native: 'Kiswahili',
    english: 'Swahili',
    fast: (
      bytes: 2167651,
      sha256:
          '395439d1ec308535066cbaea9b15e0e4cc81f8609170af76ab7e7e8d3ec42f3e',
    ),
    best: (
      bytes: 4914855,
      sha256:
          '102ebfc90724b4aebfab5bad0447ab124b7e2e82877b24895b31b0009e6fd0e0',
    ),
  ),
  OcrLanguage(
    'swe',
    native: 'Svenska',
    english: 'Swedish',
    fast: (
      bytes: 4167034,
      sha256:
          'f7304988d41f833efebcc2d529df54b1903ecebbc3da1faabd19a0fddd4fe586',
    ),
    best: (
      bytes: 14325549,
      sha256:
          '360303308aa5d4a912ac3b3637691152b7532d9bd6e960639db1affb83db7ea9',
    ),
  ),
  OcrLanguage(
    'syr',
    native: 'ܣܘܪܝܝܐ',
    english: 'Syriac',
    fast: (
      bytes: 2207208,
      sha256:
          '7435b43466da8343619bdc43c4da8dc8581f21aab3337fa1bd22ed8a8c10af04',
    ),
    best: (
      bytes: 12498294,
      sha256:
          '7642168b7731866d0ec4c74c67780913db4a04583874fcff0078daa8430bd887',
    ),
  ),
  OcrLanguage(
    'tam',
    native: 'தமிழ்',
    english: 'Tamil',
    fast: (
      bytes: 3237963,
      sha256:
          'd02fbec24be4b07e32e80d0ccfc3b6b67a3c5d61c9d0a7c8532677990912c6ec',
    ),
    best: (
      bytes: 6023201,
      sha256:
          '4b9ce85987f629dd31eaf87443a1646452a43cdf91fcf05e017382ad595dcb9e',
    ),
  ),
  OcrLanguage(
    'tat',
    native: 'Татар',
    english: 'Tatar',
    fast: (
      bytes: 1072896,
      sha256:
          '7ad946d753f4b9688e4e4bcf525a931f486da4aaa9020e32b6a7262718bdf093',
    ),
    best: (
      bytes: 7585204,
      sha256:
          '615a1d0d8b9f5c235cc6b4d3d94801371ddfdd9d63114a578c149dc1515d091a',
    ),
  ),
  OcrLanguage(
    'tel',
    native: 'తెలుగు',
    english: 'Telugu',
    fast: (
      bytes: 2769654,
      sha256:
          'd10691fddd5b67802e1c12800ebb321d3b8bcd8d24a2ac3ff206f93188c04ab5',
    ),
    best: (
      bytes: 9098795,
      sha256:
          '81b0a1cfaf8bbf0f87da72b8c348264c6f24130766f5c4ade733fc20c05aaccc',
    ),
  ),
  OcrLanguage(
    'tgk',
    native: 'Тоҷикӣ',
    english: 'Tajik',
    fast: (
      bytes: 2602685,
      sha256:
          '7b32ed1374649b9b44b9a20ed07f1e86c1e1004c3bd11ce182496a47a18cb321',
    ),
    best: (
      bytes: 4602842,
      sha256:
          'cb2f067a5d986713bd0f123f80e843e591cef1295d4af71919118652186f5852',
    ),
  ),
  OcrLanguage(
    'tha',
    native: 'ไทย',
    english: 'Thai',
    fast: (
      bytes: 1072600,
      sha256:
          '294227cc2d1292b0acb28d61d4115c88252b96d466ca90b417cf4cf0c67bf07c',
    ),
    best: (
      bytes: 7614571,
      sha256:
          'ee8adab6dc69eb8df3d3c8307ae8295471b7bd7d86a06d9267aa8f479b064eac',
    ),
  ),
  OcrLanguage(
    'tir',
    native: 'ትግርኛ',
    english: 'Tigrinya',
    fast: (
      bytes: 378822,
      sha256:
          '73d7430c22a062b061f603a2c1d70c4ea4aa092f7a932a97921926e15b4fdb3d',
    ),
    best: (
      bytes: 2410256,
      sha256:
          '5322d0ee350c09d58d16b262219e4bfd12ad29424b98f0b347c9595aab1f7e19',
    ),
  ),
  OcrLanguage(
    'ton',
    native: 'Lea faka-Tonga',
    english: 'Tongan',
    fast: (
      bytes: 947249,
      sha256:
          '23d36448a3c59499da59502419ffcaa279056fa369a0fa2c798e066321d01bd1',
    ),
    best: (
      bytes: 3729371,
      sha256:
          '64ba54baada51100cc5cb79d42b644dd6bfcdcf5f1efe76c2c53db5d3acb89c2',
    ),
  ),
  OcrLanguage(
    'tur',
    native: 'Türkçe',
    english: 'Turkish',
    fast: (
      bytes: 4550554,
      sha256:
          '7393381111e1152420fc4092cb44eef4237580d21b92bf30d7d221aad192c6b7',
    ),
    best: (
      bytes: 7456265,
      sha256:
          'e0c3338dc17503dc7d335a507c9ae01b2b46cfd07561171e1e1ac55d85e8e438',
    ),
  ),
  OcrLanguage(
    'uig',
    native: 'ئۇيغۇرچە',
    english: 'Uyghur',
    fast: (
      bytes: 2794272,
      sha256:
          '163b360268c39fc69e0c0dc9299c06dfe7a6c51ef8f33766da75022217b69b22',
    ),
    best: (
      bytes: 13074609,
      sha256:
          'e379b5ab22ff515ab645efbc2c0a683af96e058a52d29f611b9534ad7c2d824a',
    ),
  ),
  OcrLanguage(
    'ukr',
    native: 'Українська',
    english: 'Ukrainian',
    fast: (
      bytes: 3825102,
      sha256:
          'd59e53e2bded32f4445f124b4b00240fcac7e8044c003ab822ccb94f0b3db59b',
    ),
    best: (
      bytes: 10859081,
      sha256:
          '1277f6e3b6f707063a92d40e7678e7f57154e8414e328e340be9ee9275eea9c8',
    ),
  ),
  OcrLanguage(
    'urd',
    native: 'اردو',
    english: 'Urdu',
    fast: (
      bytes: 1398718,
      sha256:
          '62e8250ce2a994106e313a82e26a516a39e2cf159d0ce3c5b5008387fd0d555f',
    ),
    best: (
      bytes: 7994323,
      sha256:
          '65af3f6e50a3c3df15d7b405aab5d467e53433207745c8f5be5b8ff1a58a67c8',
    ),
  ),
  OcrLanguage(
    'uzb',
    native: 'Oʻzbek',
    english: 'Uzbek',
    fast: (
      bytes: 6470703,
      sha256:
          '0e39021eefe692906b50d9bd22e580fa57fe43fa35db6846ad8b6369ddc21ea8',
    ),
    best: (
      bytes: 12953454,
      sha256:
          '5bd8a1958b3cee68aa225774b89775f3a510dd2141e7d9eb2b5931adca2624c8',
    ),
  ),
  OcrLanguage(
    'uzb_cyrl',
    native: 'Ўзбек',
    english: 'Uzbek (Cyrillic)',
    fast: (
      bytes: 1563501,
      sha256:
          'a2fe0b3f0eb4a5e46252470160ad51cc5f3c4c0f390ba67d1911beb0dbe80cc8',
    ),
    best: (
      bytes: 4325478,
      sha256:
          '13b5f943418d362ed2a445c43777e9244ab70359bcc31a95eb89738ccd6924b1',
    ),
  ),
  OcrLanguage(
    'vie',
    native: 'Tiếng Việt',
    english: 'Vietnamese',
    fast: (
      bytes: 531275,
      sha256:
          '79df64caf7bcfb2a27df5042ecb6121e196eada34da774956995747636d5bfa1',
    ),
    best: (
      bytes: 12435550,
      sha256:
          'b6b49293d95d0b6dbd8780174627e82c75be957b6f4ed9862155540d6b00bb45',
    ),
  ),
  OcrLanguage(
    'yid',
    native: 'ייִדיש',
    english: 'Yiddish',
    fast: (
      bytes: 545606,
      sha256:
          'f9a3d74076460a505dc0c6b59a0f5bd1108c6436d570954223b3695988d1666d',
    ),
    best: (
      bytes: 3278995,
      sha256:
          '086ec92aea9c7016c74b503c3d24906381e7e57cc3f487f12e1784eb2530ba94',
    ),
  ),
  OcrLanguage(
    'yor',
    native: 'Yorùbá',
    english: 'Yoruba',
    fast: (
      bytes: 963400,
      sha256:
          '17ab3855f1ba9056183759a84e4c11cebf417a7d3c8c2cdcc37537d7fbffba3d',
    ),
    best: (
      bytes: 3736121,
      sha256:
          '3380579148d53533f0ad740b825248959067f83c3b1903c49d11652054339295',
    ),
  ),
];
