// Generates lib/src/markdown/inline/html5_entities.dart from WHATWG's
// entities.json (https://html.spec.whatwg.org/entities.json): every HTML5
// named character reference, which CommonMark decodes in text, link
// destinations and titles (spec §2.5, "Entity and numeric character
// references"). Only the names written with their `;` are kept: the spec
// recognizes no other form.
//
// Usage:
//   dart run tool/gen_html5_entities.dart path/to/entities.json
//
// ignore_for_file: avoid_print
import 'dart:convert';
import 'dart:io';

void main(List<String> args) {
  if (args.length != 1) {
    print('usage: dart run tool/gen_html5_entities.dart entities.json');
    exit(64);
  }
  final json =
      jsonDecode(File(args.single).readAsStringSync()) as Map<String, dynamic>;
  final names = <String, String>{};
  for (final MapEntry(:key, :value) in json.entries) {
    if (!key.endsWith(';')) continue;
    final characters = (value as Map<String, dynamic>)['characters'] as String;
    names[key.substring(1, key.length - 1)] = characters;
  }
  final sorted = names.keys.toList()..sort();
  final out = StringBuffer()
    ..writeln("// GENERATED by tool/gen_html5_entities.dart from WHATWG's")
    ..writeln('// entities.json — do not edit by hand.')
    ..writeln(
      '// ignore_for_file: avoid_escaping_inner_quotes, use_raw_strings',
    )
    ..writeln()
    ..writeln('/// The HTML5 named character references, name (without `&`')
    ..writeln('/// and `;`) to the characters it stands for.')
    ..writeln('const Map<String, String> html5Entities = <String, String>{');
  for (final name in sorted) {
    out.writeln('  ${_quote(name)}: ${_quote(names[name]!)},');
  }
  out.writeln('};');
  const path = 'lib/src/markdown/inline/html5_entities.dart';
  File(path)
    ..createSync(recursive: true)
    ..writeAsStringSync(out.toString());
  print('${sorted.length} entities written to $path');
}

/// [text] as a Dart string literal, every character past ASCII escaped.
String _quote(String text) {
  final out = StringBuffer("'");
  for (final rune in text.runes) {
    if (rune == 0x27 || rune == 0x5C || rune == 0x24) {
      out.write('\\${String.fromCharCode(rune)}');
    } else if (rune >= 0x20 && rune < 0x7F) {
      out.writeCharCode(rune);
    } else {
      out.write('\\u{${rune.toRadixString(16)}}');
    }
  }
  out.write("'");
  return out.toString();
}
