// Generates lib/src/ocr/ocr_language_catalog.dart: every language of
// tessdata_fast and tessdata_best at the pinned commits, with its size and
// SHA-256 (#593).
//
//   dart run tool/ocr_catalog.dart
//
// Each file is downloaded once to hash it (about 1.4 GB in all): the app
// checks what it downloads against these digests.
// ignore_for_file: avoid_print

import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';

const _fastCommit = '87416418657359cb625c412a48b6e1d6d41c29bd';
const _bestCommit = 'e12c65a915945e4c28e237a9b52bc4a8f39a0cec';
const _out = 'lib/src/ocr/ocr_language_catalog.dart';

/// Not languages: orientation detection, and the legacy-only equations.
const _skipped = {'osd', 'equ'};

Future<void> main() async {
  final client = HttpClient();
  try {
    final fast = await _hashed(client, 'tessdata_fast', _fastCommit);
    final best = await _hashed(client, 'tessdata_best', _bestCommit);
    final codes = {...fast.keys, ...best.keys}.toList()..sort();
    final missing = codes.where((c) => !_names.containsKey(c)).toList();
    if (missing.isNotEmpty) throw StateError('no name for $missing');
    final lines = StringBuffer()
      ..writeln('// GENERATED by tool/ocr_catalog.dart; do not edit.')
      ..writeln('// tessdata_fast $_fastCommit')
      ..writeln('// tessdata_best $_bestCommit')
      ..writeln()
      ..writeln("import 'package:niman/src/ocr/ocr_language.dart';")
      ..writeln()
      ..writeln('/// The tessdata_fast commit the catalog pins.')
      ..writeln("const String tessdataFastCommit = '$_fastCommit';")
      ..writeln()
      ..writeln('/// The tessdata_best commit the catalog pins.')
      ..writeln("const String tessdataBestCommit = '$_bestCommit';")
      ..writeln()
      ..writeln('/// Every language the OCR offers, by code.')
      ..writeln('const List<OcrLanguage> ocrLanguages = [');
    for (final code in codes) {
      final (native, english) = _names[code]!;
      String file((int, String)? f) =>
          f == null ? 'null' : '(bytes: ${f.$1}, sha256: ${_quote(f.$2)})';
      lines
        ..writeln('  OcrLanguage(')
        ..writeln('    ${_quote(code)},')
        ..writeln('    native: ${_quote(native)},')
        ..writeln('    english: ${_quote(english)},')
        ..writeln('    fast: ${file(fast[code])},')
        ..writeln('    best: ${file(best[code])},')
        ..writeln('  ),');
    }
    lines.writeln('];');
    File(_out).writeAsStringSync(lines.toString());
    print('wrote $_out: ${codes.length} languages');
  } finally {
    client.close();
  }
}

String _quote(String s) =>
    "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'")}'";

/// Size and SHA-256 of every `.traineddata` at [commit] of [repo], by code.
Future<Map<String, (int, String)>> _hashed(
  HttpClient client,
  String repo,
  String commit,
) async {
  final tree = await _json(
    client,
    Uri.parse(
      'https://api.github.com/repos/tesseract-ocr/$repo/git/trees/$commit',
    ),
  );
  final entries = [
    for (final e in (tree['tree']! as List).cast<Map<String, Object?>>())
      if ((e['path']! as String).endsWith('.traineddata')) e['path']! as String,
  ];
  final result = <String, (int, String)>{};
  for (final path in entries) {
    final code = path.substring(0, path.length - '.traineddata'.length);
    if (_skipped.contains(code)) continue;
    final uri = Uri.parse(
      'https://raw.githubusercontent.com/tesseract-ocr/$repo/$commit/$path',
    );
    final request = await client.getUrl(uri);
    final response = await request.close();
    if (response.statusCode != 200) {
      throw HttpException('HTTP ${response.statusCode}', uri: uri);
    }
    var bytes = 0;
    final digest = await sha256
        .bind(
          response.map((chunk) {
            bytes += chunk.length;
            return chunk;
          }),
        )
        .first;
    // A symlink in the repository comes back as its target's name
    // (tessdata_fast's frk.traineddata): not a model.
    if (bytes < 1024) {
      print('$repo $code skipped: $bytes bytes');
      continue;
    }
    result[code] = (bytes, digest.toString());
    print('$repo $code $bytes');
  }
  return result;
}

Future<Map<String, Object?>> _json(HttpClient client, Uri uri) async {
  final request = await client.getUrl(uri);
  request.headers.set(HttpHeaders.userAgentHeader, 'niman-ocr-catalog');
  final response = await request.close();
  final body = await response.transform(utf8.decoder).join();
  if (response.statusCode != 200) {
    throw HttpException('HTTP ${response.statusCode}: $body', uri: uri);
  }
  return jsonDecode(body) as Map<String, Object?>;
}

/// The name in the language itself, and in English for search.
const Map<String, (String, String)> _names = {
  'afr': ('Afrikaans', 'Afrikaans'),
  'amh': ('አማርኛ', 'Amharic'),
  'ara': ('العربية', 'Arabic'),
  'asm': ('অসমীয়া', 'Assamese'),
  'aze': ('Azərbaycan', 'Azerbaijani'),
  'aze_cyrl': ('Азәрбајҹан', 'Azerbaijani (Cyrillic)'),
  'bel': ('Беларуская', 'Belarusian'),
  'ben': ('বাংলা', 'Bengali'),
  'bod': ('བོད་ཡིག', 'Tibetan'),
  'bos': ('Bosanski', 'Bosnian'),
  'bre': ('Brezhoneg', 'Breton'),
  'bul': ('Български', 'Bulgarian'),
  'cat': ('Català', 'Catalan'),
  'ceb': ('Cebuano', 'Cebuano'),
  'ces': ('Čeština', 'Czech'),
  'chi_sim': ('简体中文', 'Chinese (Simplified)'),
  'chi_sim_vert': ('简体中文 (竖排)', 'Chinese (Simplified, vertical)'),
  'chi_tra': ('繁體中文', 'Chinese (Traditional)'),
  'chi_tra_vert': ('繁體中文 (直排)', 'Chinese (Traditional, vertical)'),
  'chr': ('ᏣᎳᎩ', 'Cherokee'),
  'cos': ('Corsu', 'Corsican'),
  'cym': ('Cymraeg', 'Welsh'),
  'dan': ('Dansk', 'Danish'),
  'deu': ('Deutsch', 'German'),
  'deu_latf': ('Deutsch (Fraktur)', 'German (Fraktur)'),
  'div': ('ދިވެހި', 'Dhivehi'),
  'dzo': ('རྫོང་ཁ', 'Dzongkha'),
  'ell': ('Ελληνικά', 'Greek'),
  'eng': ('English', 'English'),
  'enm': ('Middle English', 'Middle English'),
  'epo': ('Esperanto', 'Esperanto'),
  'est': ('Eesti', 'Estonian'),
  'eus': ('Euskara', 'Basque'),
  'fao': ('Føroyskt', 'Faroese'),
  'fas': ('فارسی', 'Persian'),
  'fil': ('Filipino', 'Filipino'),
  'fin': ('Suomi', 'Finnish'),
  'fra': ('Français', 'French'),
  'frm': ('Moyen français', 'Middle French'),
  'fry': ('Frysk', 'Western Frisian'),
  'gla': ('Gàidhlig', 'Scottish Gaelic'),
  'gle': ('Gaeilge', 'Irish'),
  'glg': ('Galego', 'Galician'),
  'grc': ('Ἀρχαία ἑλληνικά', 'Greek, Ancient'),
  'guj': ('ગુજરાતી', 'Gujarati'),
  'hat': ('Kreyòl ayisyen', 'Haitian Creole'),
  'heb': ('עברית', 'Hebrew'),
  'hin': ('हिन्दी', 'Hindi'),
  'hrv': ('Hrvatski', 'Croatian'),
  'hun': ('Magyar', 'Hungarian'),
  'hye': ('Հայերեն', 'Armenian'),
  'iku': ('ᐃᓄᒃᑎᑐᑦ', 'Inuktitut'),
  'ind': ('Bahasa Indonesia', 'Indonesian'),
  'isl': ('Íslenska', 'Icelandic'),
  'ita': ('Italiano', 'Italian'),
  'ita_old': ('Italiano antico', 'Italian (old)'),
  'jav': ('Basa Jawa', 'Javanese'),
  'jpn': ('日本語', 'Japanese'),
  'jpn_vert': ('日本語 (縦書き)', 'Japanese (vertical)'),
  'kan': ('ಕನ್ನಡ', 'Kannada'),
  'kat': ('ქართული', 'Georgian'),
  'kat_old': ('ძველი ქართული', 'Georgian (old)'),
  'kaz': ('Қазақ', 'Kazakh'),
  'khm': ('ខ្មែរ', 'Khmer'),
  'kir': ('Кыргызча', 'Kyrgyz'),
  'kmr': ('Kurmancî', 'Kurmanji (Northern Kurdish)'),
  'kor': ('한국어', 'Korean'),
  'kor_vert': ('한국어 (세로쓰기)', 'Korean (vertical)'),
  'lao': ('ລາວ', 'Lao'),
  'lat': ('Latina', 'Latin'),
  'lav': ('Latviešu', 'Latvian'),
  'lit': ('Lietuvių', 'Lithuanian'),
  'ltz': ('Lëtzebuergesch', 'Luxembourgish'),
  'mal': ('മലയാളം', 'Malayalam'),
  'mar': ('मराठी', 'Marathi'),
  'mkd': ('Македонски', 'Macedonian'),
  'mlt': ('Malti', 'Maltese'),
  'mon': ('Монгол', 'Mongolian'),
  'mri': ('Māori', 'Maori'),
  'msa': ('Bahasa Melayu', 'Malay'),
  'mya': ('မြန်မာ', 'Burmese'),
  'nep': ('नेपाली', 'Nepali'),
  'nld': ('Nederlands', 'Dutch'),
  'nor': ('Norsk', 'Norwegian'),
  'oci': ('Occitan', 'Occitan'),
  'ori': ('ଓଡ଼ିଆ', 'Odia'),
  'pan': ('ਪੰਜਾਬੀ', 'Punjabi'),
  'pol': ('Polski', 'Polish'),
  'por': ('Português', 'Portuguese'),
  'pus': ('پښتو', 'Pashto'),
  'que': ('Runasimi', 'Quechua'),
  'ron': ('Română', 'Romanian'),
  'rus': ('Русский', 'Russian'),
  'san': ('संस्कृतम्', 'Sanskrit'),
  'sin': ('සිංහල', 'Sinhala'),
  'slk': ('Slovenčina', 'Slovak'),
  'slv': ('Slovenščina', 'Slovenian'),
  'snd': ('سنڌي', 'Sindhi'),
  'spa': ('Español', 'Spanish'),
  'spa_old': ('Español antiguo', 'Spanish (old)'),
  'sqi': ('Shqip', 'Albanian'),
  'srp': ('Српски', 'Serbian'),
  'srp_latn': ('Srpski (latinica)', 'Serbian (Latin)'),
  'sun': ('Basa Sunda', 'Sundanese'),
  'swa': ('Kiswahili', 'Swahili'),
  'swe': ('Svenska', 'Swedish'),
  'syr': ('ܣܘܪܝܝܐ', 'Syriac'),
  'tam': ('தமிழ்', 'Tamil'),
  'tat': ('Татар', 'Tatar'),
  'tel': ('తెలుగు', 'Telugu'),
  'tgk': ('Тоҷикӣ', 'Tajik'),
  'tha': ('ไทย', 'Thai'),
  'tir': ('ትግርኛ', 'Tigrinya'),
  'ton': ('Lea faka-Tonga', 'Tongan'),
  'tur': ('Türkçe', 'Turkish'),
  'uig': ('ئۇيغۇرچە', 'Uyghur'),
  'ukr': ('Українська', 'Ukrainian'),
  'urd': ('اردو', 'Urdu'),
  'uzb': ('Oʻzbek', 'Uzbek'),
  'uzb_cyrl': ('Ўзбек', 'Uzbek (Cyrillic)'),
  'vie': ('Tiếng Việt', 'Vietnamese'),
  'yid': ('ייִדיש', 'Yiddish'),
  'yor': ('Yorùbá', 'Yoruba'),
};
